INDEED_URL: "https://www.indeed.com"
GOOGLE_URL: "https://www.google.com"
user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"

isHeadless: false

input_fields:
  keyword:
    selector: "#text-input-what"
    data: "travail general"
  location:
    selector: "#text-input-where"
    data: "montreal"

button_fields:
  submit_button:
    selector: "#jobsearch > div > div.css-169igj0.eu4oa1w0 > button"
  next_button:
    selector: "#jobsearch-JapanPage > div > div.css-hyhnne.e37uo190 > div > div.css-pprl14.eu4oa1w0 > nav > ul > li:nth-child(6) > a > svg"
  dismiss_button:
    selector: "#mosaic-desktopserpjapopup > div.css-g6agtu.eu4oa1w0 > button"


scraper_config:
  config_path: "config.yaml"

parser_config:
  html_folder: "html/"
  output_json_file: "results/companies.json"
  contact_filder: "contact_page/"
  contact_us_file: "contact_page/contact_us.html"
